IT-1039: Give the idp roles access to the keys
Sage-Bionetworks/synapsedev-infra pull request #73
Opened 2021-01-22 00:38 UTC by xschildw

[IT-1039] This gives the roles we use when coming in from JumpCloud the right to access the stack keys. This is necessary to delete a stack from the console. Same will be done in synapseprod for Admins only.
Note: this stack is deployed manually.

2021-01-22 16:10 UTC, zaro0508 approved these changes

2021-02-02 03:01 UTC, zaro0508 requested changes

2021-02-02 03:01 UTC, zaro0508 commented on templates/SynapseCMK-template.json
> +                                        "sts:*"
seems like too much?  i think all you need is `sts:AssumeRole` correct?

2021-02-03 21:14 UTC, xschildw commented
Closing for now, willl pick up at other end of migration.

2021-02-03 21:14 UTC, closed without merging